apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bank-app.fullname" . }}
  labels:
    {{- include "bank-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "bank-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bank-app.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "bank-app.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.probes.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startupProbe.httpGet.path }}
              port: {{ .Values.probes.startupProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.probes.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.probes.startupProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.startupProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.probes.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessProbe.httpGet.path }}
              port: {{ .Values.probes.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.probes.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.probes.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.probes.livenessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.probes.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.livenessProbe.timeoutSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.storage.enabled }}
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.storage.mountPath }}
          {{- end }}
      {{- if .Values.storage.enabled }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "bank-app.fullname" . }}-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
