{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bank-app-pvc
  labels:
    app: bank-app
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
