{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bank-app-role
  labels:
    app: bank-app
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
{{- end }}
