{{- if and .Values.storage.enabled .Values.storage.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.storageClassName }}
  labels:
    app: bank-app
provisioner: {{ .Values.storage.storageClass.provisioner }}
allowVolumeExpansion: true
volumeBindingMode: {{ .Values.storage.storageClass.volumeBindingMode }}
reclaimPolicy: {{ .Values.storage.storageClass.reclaimPolicy }}
parameters:
  {{- toYaml .Values.storage.storageClass.parameters | nindent 2 }}
{{- end }}
